### ISSUE TITLE
So let me get this straight...

### ISSUE THREAD

**Issue by BieHDC** [hfiref0x/BSODScreen#1]
instead of fixing the issues you have found and submitting a PR to fix them, you instead write a screensaver which randomly triggers some of these issues?
Are you actually trying to help or do you just like the feeling of superiority?

**Comment by hfiref0x** [comment]
Which part of "Making ReactOS Great Again Part 1" you have missed?

Must be this one?

> Q: Why this isn't reported directly to ReactOS devs?
A: Because I don't value this project as worth for any kind of official reports.

This is an issue section, not a chat section, not your forum section and not anything else. Closed.
